# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\pollyworks_viewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_viewer(object):
    def setupUi(self, viewer):
        viewer.setObjectName("viewer")
        viewer.resize(1099, 548)
        self.left = QtWidgets.QFrame(viewer)
        self.left.setGeometry(QtCore.QRect(30, 80, 501, 441))
        self.left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left.setObjectName("left")
        self.right = QtWidgets.QFrame(viewer)
        self.right.setGeometry(QtCore.QRect(560, 80, 501, 441))
        self.right.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right.setObjectName("right")
        self.frame_3 = QtWidgets.QFrame(viewer)
        self.frame_3.setGeometry(QtCore.QRect(30, 20, 51, 51))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 51, 51))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_5 = QtWidgets.QFrame(viewer)
        self.frame_5.setGeometry(QtCore.QRect(560, 20, 51, 51))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")

        self.retranslateUi(viewer)
        QtCore.QMetaObject.connectSlotsByName(viewer)

    def retranslateUi(self, viewer):
        _translate = QtCore.QCoreApplication.translate
        viewer.setWindowTitle(_translate("viewer", "neoable viewer"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    viewer = QtWidgets.QWidget()
    ui = Ui_viewer()
    ui.setupUi(viewer)
    viewer.show()
    sys.exit(app.exec_())
